name: Docs

on:
  push:
    branches: 
      - master

jobs:
  deploy-docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Fetch dependencies
        run: apt install -y doxygen

      - name: Build the documentation files
        run: |
          cd docs
          doxygen

      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.Github_Pages_Deploy }}

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.2.0
        with:
          SSH: true
          FOLDER: docs/html
          BRANCH: docs
