name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the test file
      run: |
        cd examples/simple
        mkdir build
        cd build
        cmake ..
        make
