name: CI-Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the test file
      run: |
        cd examples/simple
        mkdir build
        cd build
        cmake ..
        cmake --build . --target ALL_BUILD --config Debug -- /nologo /verbosity:minimal /maxcpucount
